### PR TITLE
Specify all units

### PR DESCRIPTION
**Pull request by knownasilya**
Only a handful were mentioned. Plus there was two places, which would make it more difficult to maintain.

### CODE REVIEW

**Comment by tchannel** [comment]
:+1:

**Comment by tchannel** [comment]
Actually, looks like the README's are auto generated from the code docblocks, which appear to be already updated. So we just need to update the readme

**Comment by tchannel** [comment]
[Fixed](https://github.com/Turfjs/turf-buffer/commit/2d3b1ed3b6890c79a6fb682f009c4daf1f45437d)

**Comment by knownasilya** [comment]
@tchannel how did you do that? Are there docs on how to generate the readme?

**Comment by tchannel** [comment]
use `npm run-script doc`. The script is defined [here](https://github.com/Turfjs/turf-buffer/blob/master/package.json#L8)

**Comment by knownasilya** [comment]
Thanks!

tip: `npm run doc` works the same :+1:

**Pull request closed without merging**
